site_name: Kotlin Companion

theme:
  name: 'material'
  language: 'pt'
  logo: 'images/kotlin-development-logo.svg'
nav:
- Home: 'index.md'
- Básico:
    - 'Porquê Kotlin?': 'porque-kotlin.md'
    - 'Tipo Básicos': 'tipos-basicos.md'
    - 'Estruturas de decisão': 'estruturas-de-decisao.md'
    - 'Estruturas de repeticão': 'estruturas-de-repeticao.md'
    - 'Funcões': 'funcoes.md'
    - 'Orientação a Objetos': 'orientacao-objetos.md'

repo_name: 'kotlin-companion'
repo_url: 'https://kotlin-companion.github.io/'
theme_dir: mkdocs-material/material

markdown_extensions:
  - admonition
  - toc:
      permalink: true
    
